export const CONFIG_COLORS = {
  border: 'hsl(var(--border))',
  input: 'hsl(var(--input))',
  ring: 'hsl(var(--ring))',
  background: 'hsl(var(--background))',
  foreground: 'hsl(var(--foreground))',
  primary: {
    DEFAULT: 'hsl(var(--primary))',
    foreground: 'hsl(var(--primary-foreground))',
  },
  secondary: {
    DEFAULT: 'hsl(var(--secondary))',
    foreground: 'hsl(var(--secondary-foreground))',
  },
  destructive: {
    DEFAULT: 'hsl(var(--destructive))',
    foreground: 'hsl(var(--destructive-foreground))',
  },
  muted: {
    DEFAULT: 'hsl(var(--muted))',
    foreground: 'hsl(var(--muted-foreground))',
  },
  accent: {
    DEFAULT: 'hsl(var(--accent))',
    foreground: 'hsl(var(--accent-foreground))',
  },
  popover: {
    DEFAULT: 'hsl(var(--popover))',
    foreground: 'hsl(var(--popover-foreground))',
  },
  card: {
    DEFAULT: 'hsl(var(--card))',
    foreground: 'hsl(var(--card-foreground))',
  },
  black: {
    a1: 'var(--black-a1)',
    a2: 'var(--black-a2)',
    a3: 'var(--black-a3)',
    a4: 'var(--black-a4)',
    a5: 'var(--black-a5)',
    a6: 'var(--black-a6)',
    a7: 'var(--black-a7)',
    a8: 'var(--black-a8)',
    a9: 'var(--black-a9)',
    a10: 'var(--black-a10)',
    a11: 'var(--black-a11)',
    a12: 'var(--black-a12)',
  },
  white: {
    a1: 'var(--white-a1)',
    a2: 'var(--white-a2)',
    a3: 'var(--white-a3)',
    a4: 'var(--white-a4)',
    a5: 'var(--white-a5)',
    a6: 'var(--white-a6)',
    a7: 'var(--white-a7)',
    a8: 'var(--white-a8)',
    a9: 'var(--white-a9)',
    a10: 'var(--white-a10)',
    a11: 'var(--white-a11)',
    a12: 'var(--white-a12)',
  },
  grey: {
    1: 'var(--grey-1)',
    2: 'var(--grey-2)',
    3: 'var(--grey-3)',
    4: 'var(--grey-4)',
    5: 'var(--grey-5)',
    6: 'var(--grey-6)',
    7: 'var(--grey-7)',
    8: 'var(--grey-8)',
    9: 'var(--grey-9)',
    10: 'var(--grey-10)',
    11: 'var(--grey-11)',
    12: 'var(--grey-12)',
    a1: 'var(--grey-a1)',
    a2: 'var(--grey-a2)',
    a3: 'var(--grey-a3)',
    a4: 'var(--grey-a4)',
    a5: 'var(--grey-a5)',
    a6: 'var(--grey-a6)',
    a7: 'var(--grey-a7)',
    a8: 'var(--grey-a8)',
    a9: 'var(--grey-a9)',
    a10: 'var(--grey-a10)',
    a11: 'var(--grey-a11)',
    a12: 'var(--grey-a12)',
  },
}
