export const CORE_TOKENS = {
  background: 'white',
  foreground: 'var(--grey-12)',
  card: 'var(--white-a12)',
  'card-foreground': 'var(--grey-12)',
  popover: 'var(--white-a12)',
  'popover-foreground': 'var(--grey-12)',
  primary: 'var(--inverse-1)',
  'primary-foreground': 'var(--inverse-12)',
  secondary: 'var(--grey-4)',
  'secondary-foreground': 'var(--grey-12)',
  muted: 'var(--grey-3)',
  'muted-foreground': 'var(--grey-10)',
  accent: 'var(--grey-4)',
  'accent-foreground': 'var(--grey-11)',
  destructive: 'var(--red-9, theme(colors.red.500))',
  'destructive-foreground': 'white',
  border: 'var(--grey-6)',
  input: 'var(--grey-7)',
  ring: 'var(--grey-8)',
}
