export const CONFIG_COLORS = {
  background: 'var(--background)',
  primary: {
    DEFAULT: 'var(--primary)',
    foreground: 'var(--primary-foreground)',
    1: 'var(--primary-1)',
    2: 'var(--primary-2)',
    3: 'var(--primary-3)',
    4: 'var(--primary-4)',
    5: 'var(--primary-5)',
    6: 'var(--primary-6)',
    7: 'var(--primary-7)',
    8: 'var(--primary-8)',
    9: 'var(--primary-9)',
    10: 'var(--primary-10)',
    11: 'var(--primary-11)',
    12: 'var(--primary-12)',
    a1: 'var(--primary-a1)',
    a2: 'var(--primary-a2)',
    a3: 'var(--primary-a3)',
    a4: 'var(--primary-a4)',
    a5: 'var(--primary-a5)',
    a6: 'var(--primary-a6)',
    a7: 'var(--primary-a7)',
    a8: 'var(--primary-a8)',
    a9: 'var(--primary-a9)',
    a10: 'var(--primary-a10)',
    a11: 'var(--primary-a11)',
    a12: 'var(--primary-a12)',
  },
  secondary: {
    DEFAULT: 'var(--secondary)',
    foreground: 'var(--secondary-foreground)',
  },
  destructive: {
    DEFAULT: 'var(--destructive)',
    foreground: 'var(--destructive-foreground)',
  },
  muted: {
    DEFAULT: 'var(--muted)',
    foreground: 'var(--muted-foreground)',
  },
  accent: {
    DEFAULT: 'var(--accent)',
    foreground: 'var(--accent-foreground)',
  },
  popover: {
    DEFAULT: 'var(--popover)',
    foreground: 'var(--popover-foreground)',
  },
  card: {
    DEFAULT: 'var(--card)',
    foreground: 'var(--card-foreground)',
  },
  black: {
    a1: 'var(--black-a1)',
    a2: 'var(--black-a2)',
    a3: 'var(--black-a3)',
    a4: 'var(--black-a4)',
    a5: 'var(--black-a5)',
    a6: 'var(--black-a6)',
    a7: 'var(--black-a7)',
    a8: 'var(--black-a8)',
    a9: 'var(--black-a9)',
    a10: 'var(--black-a10)',
    a11: 'var(--black-a11)',
    a12: 'var(--black-a12)',
  },
  white: {
    a1: 'var(--white-a1)',
    a2: 'var(--white-a2)',
    a3: 'var(--white-a3)',
    a4: 'var(--white-a4)',
    a5: 'var(--white-a5)',
    a6: 'var(--white-a6)',
    a7: 'var(--white-a7)',
    a8: 'var(--white-a8)',
    a9: 'var(--white-a9)',
    a10: 'var(--white-a10)',
    a11: 'var(--white-a11)',
    a12: 'var(--white-a12)',
  },
  grey: {
    1: 'var(--grey-1)',
    2: 'var(--grey-2)',
    3: 'var(--grey-3)',
    4: 'var(--grey-4)',
    5: 'var(--grey-5)',
    6: 'var(--grey-6)',
    7: 'var(--grey-7)',
    8: 'var(--grey-8)',
    9: 'var(--grey-9)',
    10: 'var(--grey-10)',
    11: 'var(--grey-11)',
    12: 'var(--grey-12)',
    a1: 'var(--grey-a1)',
    a2: 'var(--grey-a2)',
    a3: 'var(--grey-a3)',
    a4: 'var(--grey-a4)',
    a5: 'var(--grey-a5)',
    a6: 'var(--grey-a6)',
    a7: 'var(--grey-a7)',
    a8: 'var(--grey-a8)',
    a9: 'var(--grey-a9)',
    a10: 'var(--grey-a10)',
    a11: 'var(--grey-a11)',
    a12: 'var(--grey-a12)',
  },
  inverse: {
    1: 'var(--inverse-1)',
    2: 'var(--inverse-2)',
    3: 'var(--inverse-3)',
    4: 'var(--inverse-4)',
    5: 'var(--inverse-5)',
    6: 'var(--inverse-6)',
    7: 'var(--inverse-7)',
    8: 'var(--inverse-8)',
    9: 'var(--inverse-9)',
    10: 'var(--inverse-10)',
    11: 'var(--inverse-11)',
    12: 'var(--inverse-12)',
    a1: 'var(--inverse-a1)',
    a2: 'var(--inverse-a2)',
    a3: 'var(--inverse-a3)',
    a4: 'var(--inverse-a4)',
    a5: 'var(--inverse-a5)',
    a6: 'var(--inverse-a6)',
    a7: 'var(--inverse-a7)',
    a8: 'var(--inverse-a8)',
    a9: 'var(--inverse-a9)',
    a10: 'var(--inverse-a10)',
    a11: 'var(--inverse-a11)',
    a12: 'var(--inverse-a12)',
  },
}
